### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by enandr** [enandr/rogerenand-com#36]
- [x] open links in new tab
- [x] mobile menu close on navigate
- [x] fix spacing to the right on mobile landscape
- [ ] on mobile have navbar-fixed on always
- [ ] look at php mailer
